POST http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries

Content-Type: application/json

{
  "date": "2015-01-22",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": ["S62.5"],
  "description":"Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "discharge":{
    "date":"2015-01-28",
    "criteria":"get fast recovery"
  }
}

# {
#   "date":"2015-01-02",
#   "type":"HealthCheck",
#   "specialist":"MD House",
#   "diagnosisCodes":["S62.5","TY6.78"],
#   "description":"Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
#   "healthCheckRating":2
# }