POST http://localhost:3001/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmZhcmF6Mjk3IiwiaWQiOiI2MzJjMGY2ZWUzNTcwNzkxNzVhZTczZmQiLCJpYXQiOjE2NjUzOTcyMDd9.IYfspg8FxsU3RwyrYjC5mcjY2aHPuaAO3JFcK7H1ZDQ

{  
    "author":"Sarfaraz Hussain",
    "likes":1,
    "title":"testing6 user extractor middleware",
    "url":"samplecodemodif token.html"
}